### ISSUE TITLE
Request: Authentication

### ISSUE THREAD

**Issue by IanMoroney** [blissnd/DevOps-Orchestration-Platform#1]
Instead of having to input keys for AWS authentication (let's face it, we're all DevOps here), can we have an option that lets you use all current AWS authentication methods?
My specific example would be, if you had this platform in a docker container, I'd like to present it with environment variables, or associate it with an IAM role so that it gets creds without you having to input them.

**Comment by blissnd** [comment]
Would it be acceptable if I give you an extra button which you click and it will then import the aws credentials from ENV vars, or from ~/.aws/credentials or ~/.aws/config into the UI?

**Comment by IanMoroney** [comment]
I would say only if it's not visible in the UI.
The system should be able to read it straight from the environment
variables, or from the ~/.aws directory on the user that's running it. Same
as how the AWS cli does.

**Comment by blissnd** [comment]
One problem is the app runs as root, in order to bind to Port 80 among other reasons. It will therefore look for credentials at /root/.aws and similarly for the environment variables. This could cause more confusion than just directing users to paste the keys into the GUI.

**Comment by IanMoroney** [comment]
Well, at the moment it's intentionally insecure which means that adoption
of the tool will be low.
People nowadays present credentials or IAM roles to containers and no
longer want to store credentials in insecure ways. The AWS CLI itself
appreciates this and allows you multiple ways to authenticate.
Ideally a tool like this should follow suit and support the same ways of
presenting creds.

**Comment by blissnd** [comment]
I've made the primary requested changes:

- No longer runs as sudo and instead binds to port 6543 (http://localhost:6543)
- Allows import of AWS key ID and secret key via ENV VARs (new 'Import...' button on HTML page) of the user who started the server

This gives a good basis to continue further improvements. I would be happy if you would become a contributor to this open-source project. I'm available to give free 1:1 video training over Zoom or Mikogo including a tour of my GoLang code.
